// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGMaKc3zkNTlnIgDOuwST7ZIKNgiIUDXI',
    appId: '1:490052731843:web:bea8127aad1457f53bb376',
    messagingSenderId: '490052731843',
    projectId: 'workflow-6fdac',
    authDomain: 'workflow-6fdac.firebaseapp.com',
    storageBucket: 'workflow-6fdac.firebasestorage.app',
    measurementId: 'G-F0N2XYG2FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCirS1tb3MAHV46tnnk_Mn0Dg-MqDPKt-0',
    appId: '1:490052731843:android:ac70b831570e91b43bb376',
    messagingSenderId: '490052731843',
    projectId: 'workflow-6fdac',
    storageBucket: 'workflow-6fdac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJAtnfsEwsouyVVBhl2IfiQAcUXSvUghg',
    appId: '1:490052731843:ios:f67ec1442114d4243bb376',
    messagingSenderId: '490052731843',
    projectId: 'workflow-6fdac',
    storageBucket: 'workflow-6fdac.firebasestorage.app',
    iosBundleId: 'com.example.workflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGMaKc3zkNTlnIgDOuwST7ZIKNgiIUDXI',
    appId: '1:490052731843:web:b4b9b5f37d45526d3bb376',
    messagingSenderId: '490052731843',
    projectId: 'workflow-6fdac',
    authDomain: 'workflow-6fdac.firebaseapp.com',
    storageBucket: 'workflow-6fdac.firebasestorage.app',
    measurementId: 'G-Q6SFQ7S1J2',
  );
}
